mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=admin"
      - "MYSQL_DATABASE=admin"

php:
  build: .
  ports:
      - "8080:80"
  volumes:
      - "./:/var/www/html/"
      - "./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
  links:
    - mysql:mysql