parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    # Custom Services

    app.utils.parsehelper:
        class: AppBundle\Utils\ParseHelper
        public: true
        arguments: ["@service_container"]

    app.manager.user:
        class: AppBundle\Manager\UserManager
        public: true
        arguments: ["@app.utils.parsehelper"]


    # Custom Listeners
    app.listener.auth:
        class: AppBundle\EventSubscriber\AuthSubscriber
        public: true
        arguments: ["@service_container", "@router", "@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.listener.exception:
            class: AppBundle\EventSubscriber\ExceptionListener
            public: true
            arguments: ["@router", "@session"]
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }